### ISSUE TITLE
Add field level help for all fields

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/alerts#11]

**Comment by jwfuller** [comment]
Deliver as a google doc

**Comment by jcsparks** [comment]
I took another pass at writing field-level help.  The language should be consistent and all fields are labeled now.

**Comment by jcsparks** [comment]
I used https://datayze.com/readability-analyzer to analyze the help text; but the scores are all over the place, as each metric uses significantly different formulas to determine readability.

**Comment by jcsparks** [comment]
Added in a PR for this... @cathysnider can you review please?
