### ISSUE TITLE
Delete Article content type

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#28]
Hide Article from everyone except developers

On the node/add page, an incident is only ever a New Incident. Its description should reflect that. Suggested change: 
~~Page type used to display the timestamped updates of events relating to a specific, discrete Incident~~ to "Post information about a campus incident"

**Comment by jwfuller** [comment]
It will not be used

**Comment by tirazel** [comment]
Removed default article type from D8 base profile for future installs.
