### ISSUE TITLE
Alerts UI: Status Tab

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#29]
**Status tab** should be the default for a new incident.

**Type:** There should be a list of types to choose from, a list that is generated by the higher-ups on the Alerts team. List the types here. 

Suggested Description: "Select type of incident: (Active Harmer, Pandemic, Severe Weather, Winter Weather, High Wind and Tornadoes, Flood, Wildfire, Structure Fire, or add your own). All Incident types have boilerplate information which will be displayed in the sidebar. ~~Additionally this will allow~~ Type selection allows for identifying commonalities during a post-mortem analysis of the Incident."

**Taxonomy Sidebar:** It would be very helpful to the poster to know, at the time of incident creation, what information is contained in the Taxonomy Sidebar. Is it possible to have that information pop up on the right sidebar when the Type field is completed?

**Status:**
The following line is not necessary and add mental clutter. Keep the list items, though.
~~Used to denote the current status of this incident.~~

**Comment by jwfuller** [comment]
See #33
