### ISSUE TITLE
Alerts UI: Sidebar Tab

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#30]
Suggested Change to Description: 

Additional information to be displayed in the sidebar. Typically this will be meta information or contact information about this type of incident or this specific incident that aren't part of the ~~timeline of events~~ incident timeline. For example, contact information ~~for where to give or receive additional information about this incident~~ or general safety information ~~the public should keep in mind during this type of information~~ for this type of incident.

**Comment by jcsparks** [comment]
Changed the description as noted above, will commit the changes.
