### ISSUE TITLE
Alerts UI: Events tab

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#31]
Suggest changing Tab Title to 'Incident Updates'

**Timestamp:** this is changeable. Should it be? Can it be used to set an update for future publication?

**Timestamp description:**
The Timestamp -- Day, Date and Time -- appear in bold type as the first line of the Incident Update.

**Body description:**
Describe the incident

**Incident Update description:**
Suggested Change: Time-ordered listing of events ~~that makeup the timeline~~ for this Incident."

**Comment by jcsparks** [comment]
Made the changes, will update the page schema.
