### ISSUE TITLE
Move status fields out of tab set

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/alerts#32]
In order to keep this information visible while editing an incident, move the Title, Type, and Status fields out of the vertical tabs

**Comment by jwfuller** [comment]
See #29 
```
Status:
The following line is not necessary and add mental clutter. Keep the list items, though.
Used to denote the current status of this incident.
```

**Comment by jcsparks** [comment]
Moved Event Tab details into the Status Tab and renamed the Status Tab to Details.
