### ISSUE TITLE
Change UI element for Type field

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/alerts#33]
If possible, may a list of existing options with an 'Add new' option

**Comment by jwfuller** [comment]
From #29 
```
Status tab should be the default for a new incident.

Type: There should be a list of types to choose from, a list that is generated by the higher-ups on the Alerts team. List the types here.

Suggested Description: "Select type of incident: All Incident types have boilerplate information which will be displayed in the sidebar. Additionally this will allow Type selection allows for identifying commonalities during a post-mortem analysis of the Incident."
```

**Comment by jcsparks** [comment]
Changed the Status tab to a Details tab and added the event details content into that tab.  Removed the Event Updates tab.  Details is the default tab now.

**Comment by jcsparks** [comment]
Modified type to be displayed as a select list and added in a link to create a new taxonomy term in the type vocabulary if they need to add a new term.
