### ISSUE TITLE
Do a vocabulary check on help text

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/alerts#34]
Words like 'commonalities' and 'dissemination' are specific, but are big and may be less accessible during an incident. We should run language tests on help text to check grade level etc.

**Comment by jwfuller** [comment]
Related to #11

**Comment by jwfuller** [comment]
1. Establish a grade level to test for
1. Find a tool to use
1. Use tool

**Comment by jcsparks** [comment]
@cathysnider and I worked through updating the field-level help.  Should be good now.
