### ISSUE TITLE
Check other WYSIWYG implementations to see what features are expected

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/alerts#35]
I would expect strike-through, a character map could also be nice. We should look at popular WYSIWYG implementations like Slack or Medium for ideas

**Comment by jcsparks** [comment]
Easy enough to add in strike-through and special characters to the editor configuration.  Will work with @tirazel to get this into the profile.

**Comment by jcsparks** [comment]
Tyler and I looked a several different editor toolbars and found no universal configuration or layout.  The main commonalities seemed to be grouping the text manipulation buttons and using only icons for the functionality.  

Will add strikethrough on the editor.
