### ISSUE TITLE
Remove form elements on Incident that do not have functionality

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/alerts#37]
Promotion options do not do anything at this time

**Comment by jcsparks** [comment]
Not sure how to do this in D8.  Perhaps we can make this part of the admin theme custom codebase; I think we do it pretty easily there.  

Feel free to update if I'm missing something obvious.

**Comment by jcsparks** [comment]
Okay, you can disable these on the Manage Form Display tab of the content types.  Disabled Promoted to front page and Sticky at top of lists.  Also removed the menu options as these generally will not be on any menu.
