### ISSUE TITLE
Display Emergency Type in Alphabetical Order

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#51]
It will be a little easier for our users to find what they are looking for.

![Screen Shot 2020-02-26 at 12 04 20 PM](https://user-images.githubusercontent.com/638275/75378371-c90f9d00-5890-11ea-9b14-d68ca9baa42e.png)

**Comment by jcsparks** [comment]
There's a reset to alpha button on the taxonomy terms page.  We just need to make sure that our Editors have the correct permissions to be able to do this.

**Comment by jcsparks** [comment]
Editor Role has the ability to change the taxonomy list sort order, including reset to alphabetical.
