### ISSUE TITLE
New Incidents are Unpublished; can't be published by Editor role

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#52]
There's no way for an Editor to change these from Unpublished to Published. 

![Screen Shot 2020-02-26 at 12 16 33 PM](https://user-images.githubusercontent.com/638275/75378998-e7c26380-5891-11ea-9dda-712794e9ce17.png)

**Comment by jcsparks** [comment]
Editor Role can set all editable content types to published or unpublished now.
