### ISSUE TITLE
Taxonomy: Incident Terms - Editor needs to be able to easily access and edit the terms

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/alerts#55]
Editor cannot access Structure >> Taxonomy (except by a weird workaround); once there, Editor cannot edit terms.

Editor needs to be able to put terms in desired order; rename the term and edit the term's sidebar. 

![Screen Shot 2020-02-26 at 12 49 46 PM](https://user-images.githubusercontent.com/638275/75381726-83ee6980-5896-11ea-9274-05768d99d6cd.png)

**Comment by jcsparks** [comment]
Edit Role has permissions to edit/update the taxonomies now.
